# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)



#demo_user 
demo_user = User.create(username: 'demo_user', password: 'password')

# The Last Dance (Array of Air Jordan sneaker objects)
Sneaker.destroy_all

the_last_dance = [
    {
        name: "Air Jordan 12 Retro 'Flu Game' 2016",
        description: "The Air Jordan 12 Retro ‘Flu Game’ 2016 celebrates Michael Jordan’s legendary performance in Game 5 of the 1997 NBA Finals. Battling flu-like symptoms, Jordan lead the Bulls to a 3-2 series lead over the Utah Jazz with 38 points, 7 rebounds, 5 assists, 3 steals, and 1 block. Previously retroed in 2003 and 2009, this 2016 version stays faithful to the OG design with its black tumbled leather upper and varsity red on the mudguard and outsole.",
        release_date: "2016-05-28",
        sku: "130690 002",
        brand: "Air Jordan",
        upper_material: "Leather",
        main_color: "Black",
        colorway: "Black/Varsity Red",
        designer: "Tinker Hatfield",
        silhouette: "Air Jordan 12",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Air Jordan 4 Retro OG 'Bred' 2019",
        description: "The 2019 edition of the Air Jordan 4 ‘Bred’ celebrates the 30th anniversary of the classic silhouette, appearing in the same colorway that Michael Jordan wore when he sank ‘The Shot’ during the first round of the 1989 NBA playoffs. It’s rendered in a build that’s faithful to the original, complete with a black nubuck upper, visible Air Sole cushioning underfoot and Nike Air branding on the heel.",
        release_date: "2019-05-04",
        sku: "308497 060",
        brand: "Air Jordan",
        upper_material: "Nubuck",
        main_color: "Black",
        colorway: "Black/Cement Grey-Summit White-Fire Red",
        designer: "Tinker Hatfield",
        silhouette: "Air Jordan 4",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Air Jordan 14 Retro 'Last Shot' 2018",
        description: "Michael Jordan fans will always remember the Air Jordan 14 as the shoe Jordan was wearing when he hit the winning jumper in Game 6 of the 1998 NBA Finals. The legendary sneaker was reissued again in June 2018. All of the model’s original elements remain for this updated ‘Last Shot’ iteration, including black leather uppers and red Jumpman detailing on the heel and tongue. Its distinct, Ferrari-style medallion on the midfoot continues to serve as the standout feature of the iconic silhouette.",
        release_date: "2018-06-13",
        sku: "487471 003",
        brand: "Air Jordan",
        upper_material: "Leather",
        main_color: "Black",
        colorway: "Black/Varsity Red",
        designer: "Tinker Hatfield",
        silhouette: "Air Jordan 14",
        technology: "Zoom Air",
        category: "Lifestyle"
    },
    {
        name: "Air Jordan 6 Retro 'Infrared' 2019",
        description: "The 2019 edition of the Air Jordan 6 Retro ‘Infrared’ is true to the original colorway, which Michael Jordan wore when he captured his first NBA title. Dressed primarily in black nubuck with a reflective 3M layer underneath, the mid-top features Infrared accents on the midsole, heel tab and lace lock. Nike Air branding adorns the heel and sockliner, an OG detail last seen on the 2000 retro.",
        release_date: "2016-05-28",
        sku: "130690 001",
        brand: "Air Jordan",
        upper_material: "Leather",
        main_color: "Black",
        colorway: "Black/Varsity Red",
        designer: "Tinker Hatfield",
        silhouette: "Air Jordan 6",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Air Jordan 11 Retro 'Space Jam' 2016",
        description: "The Air Jordan 11 Retro ‘Space Jam’ 2016 commemorates the 20th anniversary of the movie ‘Space Jam.’ Worn by Michael Jordan as a Player Exclusive (PE) in both the movie and the 1995 NBA Playoffs, the 2016 retro ended up being Nike’s largest and most successful shoe launch ever. This 2016 sneaker is a more faithful reproduction of the original PE than the 2000 and 2009 retros. The sneaker also swaps the traditional #23 for MJ’s comeback #45 on the heel, a first for an Air Jordan 11 retail release.",
        release_date: "2016-12-09",
        sku: "378037 003",
        brand: "Air Jordan",
        upper_material: "Leather",
        main_color: "Black",
        colorway: "Black/Concord-White",
        designer: "Tinker Hatfield",
        silhouette: "Air Jordan 11",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Air Jordan 11 Retro 'Bred' 2019",
        description: "The Air Jordan 11 Retro 'Bred' 2019 brings back an original colorway initially debuted in 1995. The Tinker Hatfield-designed silhouette features Chicago Bulls colors, with black mesh on the upper sitting atop shiny black patent leather. A white midsole melds nicely with a translucent Varsity Red outsole, and is the same colorway that Michael Jordan wore during the 1996 NBA championship playoff run. This retro was distributed in December 2019 with OG detailing, including high-cut patent leather, signature Jumpman branding and MJ's number 23 stamped on the heel.",
        release_date: "2019-12-14",
        sku: "378037 061",
        brand: "Air Jordan",
        upper_material: "Patent Leather",
        main_color: "Red",
        colorway: "Black/White/Varsity Red",
        designer: "Tinker Hatfield",
        silhouette: "Air Jordan 11",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Air Jordan 8 Retro 'Playoff' 2013",
        description: "The Nike Air Jordan 8 Retro 'Playoff' 2013 is a retro re-release of the sneaker worn by Michael Jordan during Game 6 of the 1993 NBA Finals against the Phoenix Suns. The win sealed Michael Jordan and the Bulls' first three-peat NBA Championship and gave Jordan his third-straight Finals MVP. Staying faithful to the original design, the 'Playoff' features a black nubuck suede upper with white, black, and True Red graphical overlays at the ankles. The most noticeable difference between the 1993 model and the 2013 retro is the True Red heel tab found on the OG '93 sneakers has been changed to black on the 2013 retro. The Air Jordan 8 Retro 'Playoff' was also retro released in 2007.",
        release_date: "2013-06-29",
        sku: "305381 061",
        brand: "Air Jordan",
        upper_material: "Durabuck",
        main_color: "Black",
        colorway: "Black/Varsity Red-White-Bright Concord",
        designer: "Tinker Hatfield",
        silhouette: "Air Jordan 8",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Air Jordan 7 Retro 'Raptor' 2012",
        description: "The Nike Air Jordan 7 Retro 'Raptor' 2012 offers a version of the OG 1992 colorway that's also been retro-released in 2002 and 2009. The design combines a black nubuck upper with True Red and Club Purple accents. Released in September 2012, the colorway gets its nickname from its similarity to the Toronto Raptors team colors.",
        release_date: "2012-09-01",
        sku: "304775 018",
        brand: "Air Jordan",
        upper_material: "Nubuck",
        main_color: "Black",
        colorway: "Black/Tr Rd-Drk Chrcl-Clb Prpl",
        designer: "Tinker Hatfield",
        silhouette: "Air Jordan 7",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Air Jordan 1 Retro High OG 'Chicago' 2015",
        description: "The Air Jordan 1 Retro High OG 'Chicago' 2015 colorway was designed to avoid Jordan's $5,000-per game fines from the NBA after the original black and red colorway was banned. The 'Chicago' was first retroed in 1994 and stayed true to the 1985 design. Further retros were released in 2013 with small changes to the design, and again in 2015 with the original branding details: the Nike Air logo on the tongue and the original clean heel without the Jumpman logo.",
        release_date: "2015-05-29",
        sku: "555088 101",
        brand: "Air Jordan",
        upper_material: "Leather",
        main_color: "Red",
        colorway: "White/Black-Varsity Red",
        designer: "Peter Moore",
        silhouette: "Air Jordan 1",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Air Jordan 13 Retro 'Flint' 2020",
        description: "Released in the spring of 2020, the Air Jordan 13 Retro 'Flint' 2020 brings back an OG colorway in grey and 'French Blue.' Including its late-90s debut, this is the fourth time the cool colorway has been executed on the AJ13. Unlike the last iteration rolled out in 2010, this version features the reflective detailing that made the original unique. Constructed with smooth grey suede and 'cat's-paw' traction underfoot, this sneaker is a blend of streamlined style and raw power.",
        release_date: "2020-05-30",
        sku: "414571 404",
        brand: "Air Jordan",
        upper_material: "Textile",
        main_color: "Blue",
        colorway: "Navy/Carolina Blue/Flint Grey/White",
        designer: "Tinker Hatfield",
        silhouette: "Air Jordan 13",
        technology: "Zoom",
        category: "Lifestyle"
    },
    {
        name: "Air Jordan 3 Retro '88' 2013",
        description: "In 2013, the Jordan Brand released the Air Jordan 3 Retro 88 commemorating the 25th anniversary of Jordan's free-throw line dunk. The sneaker even launched at 3:51 pm, the exact time Jordan took off and sealed his victory. This was the first Jordan Retro to feature NIKE AIR branding on the heel since the first 1994 retros.",
        release_date: "2016-12-09",
        sku: "580775 160",
        brand: "Air Jordan",
        upper_material: "Leather",
        main_color: "Black",
        colorway: "Black/Concord-White",
        designer: "Tinker Hatfield",
        silhouette: "Air Jordan 11",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Air Jordan 11 Retro Low 'Concord-Bred'",
        description: "The Air Jordan 11 Retro Low 'Concord-Bred' combines two iconic OG colorways of the original mid-top silhouette. The upper replicates the look of the ‘Concord’ Air Jordan 11, featuring a white leather upper with a signature patent leather overlay in contrasting black and unexpected red branding elements at the tongue and heel. A white foam midsole gives way to a semi-translucent red rubber outsole, borrowed from the ‘Bred’ Air Jordan 11.",
        release_date: "2020-06-20",
        sku: "AV2187 160",
        brand: "Air Jordan",
        upper_material: "Patent Leather",
        main_color: "White",
        colorway: "Black/Concord-White",
        designer: "Tinker Hatfield",
        silhouette: "Air Jordan 11",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Air Jordan 5 Retro 'Fire Red' 2020",
        description: "The 2020 edition of the Air Jordan 5 Retro ‘Fire Red’ brings back the OG colorway of the classic silhouette on the occasion of its 30th anniversary. The build is faithful to the original, featuring a white leather upper with a silver reflective tongue and Nike Air branding on the heel. The black midsole, embellished with red shark tooth detailing inspired by a WWII P-51 Mustang fighter plane, is reinforced by an icy translucent outsole.",
        release_date: "2020-05-02",
        sku: "DA1911 102",
        brand: "Air Jordan",
        upper_material: "Leather",
        main_color: "Red",
        colorway: "True White/Fire Red/Black/Metallic Silver",
        designer: "Tinker Hatfield",
        silhouette: "Air Jordan 5",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Air Jordan 1 Retro High OG 'Royal Toe'",
        description: "The Air Jordan 1 Retro High OG 'Royal Toe' applies a familiar blend of colors to the iconic silhouette. The all-leather upper features a white base with contrasting black overlays and pops of Game Royal at the collar, toe box and rubber outsole. A lightly padded nylon tongue in black is topped with a Nike Air tongue tag, while the classic Jordan Wings logo appears in white on the lateral collar flap.",
        release_date: "2020-05-09",
        sku: "555088 041",
        brand: "Air Jordan",
        upper_material: "Leather",
        main_color: "Blue",
        colorway: "Black/White/Game Royal/Black",
        designer: "Peter Moore",
        silhouette: "Air Jordan 1",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Air Jordan 2 Retro 'Chicago Home'",
        description: "Produced in Italy, the Air Jordan 2 comes with faux lizard skin on the upper, a full-length Nike Air midsole, and a Swoosh-less design. The sneaker was revolutionary in that it was one of the first basketball shoes to feature a soft midsole from heel to toe. After it's original release in 1987, the Air Jordan 2 saw its first retro in 1994. Rumor has it the original molds were lost or stolen and the sneaker wouldn't retro until 2004. The sneaker returned to shelves in 2008 as part of the Jordan 21/2 Collezione 'Countdown' Pack, again in 2010, and most recently in 2014.",
        release_date: "2014-06-07",
        sku: "385475 102",
        brand: "Air Jordan",
        upper_material: "Leather",
        main_color: "White",
        colorway: "White/Black-Vrsty Red-Cmnt Gry",
        designer: "Bruce Kilgore",
        silhouette: "Air Jordan 2",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Air Jordan 2 Retro '2004'",
        description: "In 1986, Bruce Kilgore defied conventional footwear design with the Air Jordan 2. He stripped the shoe of intricacies and focused instead on the asymmetrical and textural aspects while still maintaining maximum performance elements. Re-released in 2004, the Air Jordan 2 Retro ‘2004’ sports the original color scheme, with a white leather upper and black detailing on the laces, lining and midsole. The colorway is highlighted by the Varsity Red accents on the heel counter, outsole, lining and tab.",
        release_date: "2004-03-27",
        sku: "308308 161",
        brand: "Air Jordan",
        upper_material: "Leather",
        main_color: "White",
        colorway: "White/Varsity Red-Black",
        designer: "Bruce Kilgore",
        silhouette: "Air Jordan 2",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Air Jordan 3 Retro OG 'Black Cement' 2018",
        description: "The Air Jordan 3 was the first of many for Michael Jordan and Tinker Hatfield. It was the first time they would work together on the signature shoe, it was the first time the elephant print made an appearance on a shoe, and it was the first time the “Jumpman” logo adorned the tongue with the classic “NIKE AIR” stamped on the heel. The Black/Cement Air Jordan 3 Retro OG comes back in its original form. Featuring black tumbled and smooth leather uppers and all the distinct details we remember thirty years later.",
        release_date: "2018-02-17",
        sku: "854262 001",
        brand: "Air Jordan",
        upper_material: "Leather",
        main_color: "Black",
        colorway: "Black/Cement Grey-White-Fire Red",
        designer: "Tinker Hatfield",
        silhouette: "Air Jordan 3",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Air Jordan 3 Retro OG 'True Blue' 2016",
        description: "The Air Jordan 3 Retro OG ‘True Blue’ was released as one of the four OG colorways in 1988. It saw several non-OG retro releases, starting in 2001, in 2009 (Europe only), and again in 2011 as part of a wide Air Jordan 3 retro release that commemorated the 23rd anniversary of the shoe. The 2016 retro saw the ‘True Blue’ return again, but this time with the original branding and logo details that mimic the 1988 release.",
        release_date: "2016-11-25",
        sku: "854262 106",
        brand: "Air Jordan",
        upper_material: "Leather",
        main_color: "White",
        colorway: "White/True Blue",
        designer: "Tinker Hatfield",
        silhouette: "Air Jordan 3",
        technology: "Air",
        category: "Lifetyle"
    },
    {
        name: "Air Jordan 4 Retro 'Cement' 2012",
        description: "The Air Jordan 4 Retro 'Cement’ 2012 combines a white leather upper with Fire Red, Black, and speckled Cement Grey accents. Released in 1989 as one of the four original colorways, the sneaker was retro’d in 1999 and 2016, but this 2012 Air Jordan 4 Retro 'Cement’ is the only version that swaps the OG Nike Air branding for a Jumpman logo on the heel.",
        release_date: "2012-02-18",
        sku: "308497 103",
        brand: "Air Jordan",
        upper_material: "Leather",
        main_color: "White",
        colorway: "White/Black-Cement Grey",
        designer: "Tinker Hatfield",
        silhouette: "Air Jordan 4",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Air Jordan 10 Retro 'Shadow' 2018",
        description: "The Air Jordan 10 ’Shadow’ gets a true retro that resembles the 1994 original. Featuring a Dark Shadow nubuck and black tumbled leather upper with a black midsole, True Red accents appear on the Jumpman logo on the heel and outsole. The only other time this colorway came back was during the 2008 Countdown Pack with the Air Jordan 13. That version featured a ‘23’ embroidered on the side profile and a distinctly different shade of grey.",
        release_date: "2018-04-21",
        sku: "310805 002",
        brand: "Air Jordan",
        upper_material: "Leather",
        main_color: "Black",
        colorway: "Dark Shadow/Black-True Red",
        designer: "Tinker Hatfield",
        silhouette: "Air Jordan 10",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Air Jordan 10 'Double Nickel'",
        description: "Released in March of 2015, the Air Jordan 10 ‘Double Nickel’ celebrates the player exclusive Air Jordan 10 ‘Chicago’ worn by Jordan on his return to the NBA in 1995. ‘Double Nickel’ references the 55 points he scored against the New York Knicks at Madison Square Garden after a stint in Minor League baseball. This 2015 version delivers a more faithful reproduction of the original 1995 Air Jordan 10 ‘Chicago’ colorway than the 2012 ‘Chicago’ in its shape, materials, and detailing.",
        release_date: "2015-03-28",
        sku: "310805 102",
        brand: "Air Jordan",
        upper_material: "Leather",
        main_color: "White",
        colorway: "White/Varsity Red-Black",
        designer: "Tinker Hatfield",
        silhouette: "Air Jordan 10",
        technology: "Air",
        category: "Lifestyle"
    }
]

#Off-White Collection
off_white = [
    {
        name: "OFF-WHITE x Air Jordan 1 Retro High OG 'UNC'",
        description: "Inspired by Michael Jordan’s alma mater, the Off-White x Air Jordan 1 Retro High OG ‘UNC’ carries a classic two-tone composition, filtered through Virgil Abloh’s unique design prism. The process involves taking a white leather base with dark powder blue overlays and adding embellishments that convey an expressive, handmade quality. They include detached Wings, a floating Swoosh, and lines of text on the medial-side quarter panel delineating the taxonomy of the shoe.",
        release_date: "2018-05-23",
        sku: "AQ0818 148",
        brand: "Air Jordan",
        upper_material: "Leather",
        main_color: "Blue",
        colorway: "White/Dark Powder Blue-Cone",
        designer: "Peter Moore",
        silhouette: "Air Jordan 1",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "OFF-WHITE x Air Jordan 5 Retro SP 'Muslin'",
        description: "The OFF-WHITE x Air Jordan 5 SP 'Muslin' delivers Virgil Abloh’s stylized take on the retro silhouette. The faded black textile upper blends traditional details, including a silver reflective tongue and embroidered Nike Air branding, with Virgil’s signature text on the laces and medial-side quarter panel. A pre-yellowed translucent rubber outsole adds to the sneaker’s vintage aesthetic.",
        release_date: "2020-02-15",
        sku: "CT8480 001",
        brand: "Air Jordan",
        upper_material: "Leather",
        main_color: "Black",
        colorway: "Black/Fire Red/Muslin",
        designer: "Tinker Hatfield",
        silhouette: "Air Jordan 5",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "OFF-WHITE x Air Max 90 'Black'",
        description: "The Off-White x Air Max 90 ‘Black’ offers a unique blend of materials on the upper, which combines a ripstop base with nubuck overlays and a suede mudguard. The all-black finish is contrasted by a white Swoosh with zigzag stitching, a small orange tab on the quarter panel and orange stitching on the exposed-foam tongue. Virgil Abloh’s signature text block makes an appearance on the shoe’s medial side.",
        release_date: "2019-02-07",
        sku: "AA7293 001",
        brand: "Nike",
        upper_material: "Nubuck",
        main_color: "Black",
        colorway: "Black/Black/Cone/White",
        designer: "Tinker Hatfield",
        silhouette: "Air Max 90",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "OFF-WHITE x Air Jordan 1 Retro High OG 'Chicago'",
        description: "Created by designer Virgil Abloh, the Air Jordan 1 x OFF-WHITE comes in the classic Chicago colorway. Some of the sneakers' half-finished features include a Swoosh connected to the shoe with visible blue stitching, 'Air' printed on the midsole, and an OFF-WHITE zip tie on the collar. The box comes deconstructed as it's been turned inside-out with the inside consisting of a black base and gold Jumpman logo, while the outside is plain cardboard with the words 'Jumpman' printed on it. Virgil's OFF-WHITE collection included remixed iterations of the Air VaporMax, Air Presto, Air Max 90, Blazer, Air Max 97, Hyperdunk 2017, Air Force 1, Zoom Fly, and Chuck Taylor.",
        release_date: "2017-09-06",
        sku: "AA3834 101",
        brand: "Air Jordan",
        upper_material: "Leather",
        main_color: "Red",
        colorway: "White/Black-Varsity Red-Black",
        designer: "Peter Moore",
        silhouette: "Air Jordan 1",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "OFF-WHITE x Air Presto 'Black'",
        description: "This monochromatic take on the Air Presto is the second time Virgil Abloh and Nike collaborated on this iconic silhouette. The July 2018 iteration came a few mere months after it’s two-tone predecessor made it’s debut as part of Abloh and Nike’s ‘The Ten’ Collection. This pair showcases an all-black finish, accented with unique touches including a plastic zip tie, white Swoosh with conspicuous zig-zag stitching, and lines of text on the medial quarter panel that allude to the shoe’s Beaverton origins.",
        release_date: "2018-07-27",
        sku: "AA3830 002",
        brand: "Nike",
        upper_material: "Leather",
        main_color: "Black",
        colorway: "Black/White/Cone",
        designer: "Tobie Hatfield",
        silhouette: "Air Presto",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "OFF-WHITE x Air Force 1 Low 'Black'",
        description: "Virgil Abloh presents a relatively straightforward take on Bruce Kilgore’s design with this OFF-WHITE x Air Force 1 Low. That isn’t to suggest there aren’t unique details on the reconstructed build: in addition to a mix of ripstop and suede, the upper features taped seams and a white Swoosh attached via zigzag stitching. Exposed foam and misplaced tags appear on the tongue, while ‘LOGO’ inscribed on the heel tab delivers a final meta flourish.",
        release_date: "2018-12-19",
        sku: "AO4606 001",
        brand: "Nike",
        upper_material: "Leather",
        main_color: "Black",
        colorway: "Black/White-Cone-Black",
        designer: "Bruce Kilgore",
        silhouette: "Air Force 1",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "OFF-WHITE x Air VaporMax 'Part 2'",
        description: "Virgil Abloh teamed up with Nike to release an all-black Air VaporMax in March 2018, a spiritual successor to Abloh's VaporMax design from ‘The Ten' collection. The OFF-WHITE x Air VaporMax ‘Part 2’ features a black Flyknit upper with matching laces and a Swoosh logo accented by a red zip tie. Abloh's signature lettering on the medial side and a translucent VaporMax unit complete the look.",
        release_date: "2018-03-30",
        sku: "AA3831 002",
        brand: "Nike",
        upper_material: "Leather",
        main_color: "Black",
        colorway: "Black/Total Orange-Clear",
        designer: "Andreas Harlow",
        silhouette: "Air Vapormax",
        technology: "Air",
        category: "Running"
    },
    {
        name: "OFF-WHITE x Air Max 90 'Desert Ore'",
        description: "The Off-White x Air Max 90 ‘Desert Ore’ represents yet another of Virgil Abloh’s fanciful takes on the retro silhouette. Unlike its stark black and white counterparts, this pair features a mixed-material upper dressed in a warm tan shade. A stitched-on in Swoosh in Bright Mango is joined by the usual Virgil flourishes, including a blue zip tie and lines of printed text on the medial side.",
        release_date: "2019-02-07",
        sku: "AA7293 200",
        brand: "Nike",
        upper_material: "Suede",
        main_color: "Tan",
        colorway: "Desert Ore/Desert Ore/Hyper Jade/Bright Mango",
        designer: "Tinker Hatfield",
        silhouette: "Air Max 90",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "OFF-WHITE x Wmns Waffle Racer 'Vivid Sky'",
        description: "Nike and Virgil Abloh’s OFF-WHITE extend their collaborative quest to reimagine the Wmns Waffle Racer as part of a three-sneaker pack fusing utility and retro track style. Introduced in December 2019, this women's edition carries a Vivid Sky upper shrouded in translucent textile, a trio of contrast Swooshes and neon cording traversing the laces. An updated logo is stitched to the tongue. Under a matching foam midsole, the iconic rubber Waffle outsole utilizes a racing spike motif.",
        release_date: "2019-12-12",
        sku: "CD8180 400",
        brand: "Nike",
        upper_material: "Leather",
        main_color: "Blue",
        colorway: "Vivid Sky/Black/Electric Green",
        designer: "-",
        silhouette: "Waffle Racer",
        technology: "Air",
        category: "Running"
    },
    {
        name: "OFF-WHITE x Air Presto 'White'",
        description: "The white colorway of the Off-White x Air Presto released in August 2018, a week after its all-black counterpart hit shelves. The lifestyle runner combines a deconstructed build – highlighted by rough seams and the exposed inner foam of the tongue – with the heralded T-shirt-like comfort of the original Nike Air Presto from 2000. Virgil Abloh’s signature flourishes are present and accounted for, including a plastic zip tie and printed block-letter text flanked by quotation marks.",
        release_date: "2018-08-03",
        sku: "AA3830 100",
        brand: "Nike",
        upper_material: "-",
        main_color: "White",
        colorway: "White/Black/Cone",
        designer: "Tobie Hatfield",
        silhouette: "Air Presto",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "OFF-WHITE x Air VaporMax 'Part 2'",
        description: "The April 2018 version of Virgil Abloh’s all-white Air VaporMax is mostly unchanged from the original pair from ‘The Ten.’ Stripped of color, the performance runner brings raw materials and unique details to the forefront, including an exposed-foam tongue, translucent Swoosh and off-white suede eyestay. Printed above the clear VaporMax unit, the quotation ‘AIR’ print on the lateral side takes on an extra meta dimension.",
        release_date: "2018-04-14",
        sku: "AA3831 100",
        brand: "Nike",
        upper_material: "Flyknit",
        main_color: "White",
        colorway: "White/Total Orange-Black",
        designer: "Andreas Harlow",
        silhouette: "Air Vapormax",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "OFF-WHITE x Air Jordan 1 Retro High OG 'White' 2018",
        description: "Inspired by Air Jordan 1 colorways, the OFF-WHITE x Air Jordan 1 Retro High OG 'White' 2018 is a reimagination of its 'Chicago'-themed predecessor. Designed by Virgil Abloh, the model features an all-white premium leather and mesh upper with deconstructed Swoosh branding and blue detailing, and Wings logos on the ankles. It is accented by black “AIR” lettering on the midsole, black 'Off-White™ for NIKE' text on the side panels, and orange tabs.",
        release_date: "2018-03-03",
        sku: "AQ0818 100",
        brand: "Air Jordan",
        upper_material: "Leather",
        main_color: "White",
        colorway: "White/White",
        designer: "Peter Moore",
        silhouette: "Air Jordan 1",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "OFF-WHITE x Zoom Fly SP 'Black'",
        description: "The OFF-WHITE x Zoom Fly SP ‘Black’ features a deconstructed take on the performance runner. Highlighted by an unlined translucent upper with Virgil Abloh’s signature text on the shoe’s medial side, the shoe also sports exposed stitch detailing, most noticeably on the white Swoosh. A black Lunarlon midsole, embedded with a carbon-infused nylon plate, features ‘FOAM’ printed on the lateral side.",
        release_date: "2018-12-14",
        sku: "AJ4588 001",
        brand: "Nike",
        upper_material: "Leather",
        main_color: "Black",
        colorway: "Black/White-Cone",
        designer: "Erick Goto",
        silhouette: "Zoom Fly",
        technology: "Lunarlon",
        category: "Running"
    },
    {
        name: "OFF-WHITE x Zoom Fly SP 'Tulip Pink'",
        description: "With the OFF-WHITE x Zoom Fly SP ‘Tulip Pink,’ Virgil Abloh’s signature touches—including printed text on the midsole, laces and medial quarter panel—are overshadowed by the shoe’s vibrant color scheme. The design makes use of clashing shades of Tulip Pink and Racer Pink on the structural elements of the translucent upper, as well as the stitched-on Swoosh and Lunarlon midsole.",
        release_date: "2018-11-28",
        sku: "AJ4588 600",
        brand: "Nike",
        upper_material: "Leather",
        main_color: "Pink",
        colorway: "Tulip Pink/Racer Pink",
        designer: "Erick Goto",
        silhouette: "Zoom Fly",
        technology: "Lunarlon",
        category: "Running"
    },
    {
        name: "OFF-WHITE x Air Presto 'The Ten'",
        description: "The Off-White x Air Presto was released as part of ‘The Ten’ — a collaborative capsule from Virgil Abloh and Nike exploring ten classic silhouettes through two distinct themes: ‘Revealing,’ featuring hand-cut and reconstructed builds, and ‘Ghosting,’ characterized by translucent uppers. Grouped in the former category, the Air Presto is updated with unique details like a tonal Swoosh on the mesh upper, plastic zip tie, and ‘AIR’ printed on the heel strap.",
        release_date: "2017-09-06",
        sku: "AA3830 001",
        brand: "Nike",
        upper_material: "Leather",
        main_color: "Black",
        colorway: "Black/Black-Muslin",
        designer: "Tobie Hatfield",
        silhouette: "Air Presto",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "OFF-WHITE x Air Max 97 'Menta'",
        description: "The OFF-WHITE x Air Max 97 ‘Menta’ features a translucent textile upper finished in Wolf Grey, complemented by Virgil Abloh’s signature text and tonal zigzag stitching throughout. The neutral color scheme is disrupted by a multicolored Swoosh that transitions from green to blue to red, while underfoot, a smoky grey rubber outsole maintains the shoe’s translucent theme.",
        release_date: "2018-10-18",
        sku: "AJ4585 101",
        brand: "Nike",
        upper_material: "Leather",
        main_color: "Grey",
        colorway: "Off White/Wolf Grey-White-Menta",
        designer: "Christian Treeser",
        silhouette: "Air Max 97",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "OFF-WHITE x Air VaporMax 'The Ten'",
        description: "Released at Nikelab stores in September of 2017, the OFF-WHITE x Air VaporMax was part of Virgil Abloh's 10-pair collaboration with Nike and quickly became one of the most coveted kicks of the year. The design features a black Flyknit upper with an oversized white stitched Swoosh, orange accents, and a full-length blacked-out Air VaporMax sole. The sneaker also includes a retro-style tongue and the collection's quotation mark motif can be found on the shoelaces and side panels.",
        release_date: "2017-09-06",
        sku: "AA3831 001",
        brand: "Nike",
        upper_material: "Flyknit",
        main_color: "Black",
        colorway: "Black/White-Clear",
        designer: "Andreas Harlow",
        silhouette: "Air VapormMax",
        technology: "Air",
        category: "Running"
    },
    {
        name: "OFF-WHITE x Air Max 97 OG 'The Ten'",
        description: "Released as part of ‘The Ten’ collection from November 2017, Virgil Abloh’s take on the Air Max 97 focuses on the shoe’s upper. The retro runner’s translucent build serves to tone down the visual impact of its signature wavy lines, so that the eye is drawn to the overall shape instead. ‘AIR’ stamped on the lateral side serves as a reminder of the technical innovation inherent in the '97 – the first Nike silhouette to feature a full-length Max Air unit.",
        release_date: "2017-11-18",
        sku: "AJ4585 100",
        brand: "Nike",
        upper_material: "Leather",
        main_color: "White",
        colorway: "White",
        designer: "Christian Tresser",
        silhouette: "Air Max 97",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "OFF-WHITE x Air Max 97 'Black'",
        description: "Debuting on the runway at Paris Fashion Week in June 2018, the OFF-WHITE x Air Max 97 in black sees Virgil Abloh outfit the retro runner with a translucent textile upper. A white Swoosh and ‘AIR’ lettering adorn the lateral side, while the quarter panel on the medial side is printed with more lines of Virgil’s signature text. The shoe’s reconstructed look is finished with a woven Nike tongue tag pushed to the side.",
        release_date: "2018-10-18",
        sku: "AJ4585 001",
        brand: "Nike",
        upper_material: "Leather",
        main_color: "Black",
        colorway: "Black/Cone-Black-White",
        designer: "Christian Tresser",
        silhouette: "Air Max 97",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "OFF-WHITE x Hyperdunk 2017 Flyknit 'The Ten'",
        description: "What sets apart the Off-White x Hyperdunk from the majority of sneakers from ‘The Ten’ – the collection of collaborative sneakers from Virgil Abloh and Nike – is that it’s a pure performance sneaker. Underneath the translucent components, including an added midfoot strap, is a breathable knit upper, mounted atop a React foam midsole. Virgil’s suite of signature design embellishments gives the shoe a cohesive design language that makes the built-in technology relatable and wearable for lifestyle.",
        release_date: "2017-11-12",
        sku: "AJ4578 100",
        brand: "Nike",
        upper_material: "Flyknit",
        main_color: "White",
        colorway: "White/White-White",
        designer: "Leo Chang",
        silhouette: "Hyperdunk 2017",
        technology: "React",
        category: "Lifestyle"
    },
    {
        name: "OFF-WHITE x Blazer Mid 'Grim Reapers'",
        description: "Releasing alongside an accompanying ‘All Hallow’s Eve’ colorway in orange, the OFF-WHITE x Blazer Mid ‘Grim Reapers’ completes Virgil Abloh’s Halloween-themed sneaker pack. The black and grey upper sports contrast orange stitching in celebration of the October holiday, along with an oversized white Swoosh, blue zip tie and OFF-WHITE lettering on the quarter panel of the shoe’s medial side.",
        release_date: "2018-10-03",
        sku: "AA3832 001",
        brand: "Nike",
        upper_material: "Leather",
        main_color: "Black",
        colorway: "Black/Cone-Black-White",
        designer: "Bill Bowerman",
        silhouette: "Blazer",
        technology: "Air",
        category: "Lifestyle"
    }
]

# YEEZY COLLECTION

yeezy_collection = [
    {
        name: "Yeezy Boost 350 V2 'Zebra'",
        description: "Released on February 25, 2017, the Yeezy Boost 350 V2 ‘Zebra’ combines a white/core black Primeknit upper with red SPLY 350 branding and a translucent white midsole housing full-length Boost. Sold exclusively at adidas.com, Yeezy Supply, and select adidas flagship stores, the ‘Zebra’ sold out instantly but was restocked on June 24th, 2017. Another restock of the ‘Zebra’ arrived November 16, 2018, with more pairs hitting the marketplace and delivering on Kanye’s promise of Yeezy’s being more accessible to anyone that wanted them.",
        release_date: "2017-02-25",
        sku: "CP9654",
        brand: "Adidas",
        upper_material: "Primeknit",
        main_color: "White",
        colorway: "White/Core Black/Red",
        designer: "Kanye West",
        silhouette: "Yeezy Boost 350",
        technology: "Boost",
        category: "Lifestyle"
    },
    {
        name: "Yeezy Boost 700 'Wave Runner'",
        description: "This inaugural colorway of Kanye West’s Yeezy Wave Runner 700 launched in November 2017, following a public debut earlier in the year as part of the Yeezy Season 5 runway show. The sneaker’s retro-inspired lines worked in tandem with a chunky silhouette reminiscent of an earlier era. A mesh base is finished in grey on the quarter panels and bright blue and teal on the forefoot. Suede overlays arrive on the toe and heel accented grey leather eyestays. Other details include neon green laces, a bulky white midsole, and pops of black and bright orange.",
        release_date: "2017-10-31",
        sku: "B75571",
        brand: "Adidas",
        upper_material: "Primeknit",
        main_color: "Suede",
        colorway: "Solid Grey/Chalk White/Core Black",
        designer: "Kanye West",
        silhouette: "Yeezy Boost 350",
        technology: "Boost",
        category: "Lifestyle"
    },
    {
        name: "Yeezy Boost 350 V2 'Cream White / Triple White'",
        description: "First released on April 29, 2017, the Yeezy Boost 350 V2 ‘Cream White’ combines a cream Primeknit upper with tonal cream SPLY 350 branding, and a translucent white midsole housing full-length Boost. Released again in October 2018, this retro helped fulfill Kanye West’s oft-repeated ‘YEEZYs for everyone’ Twitter mantra, as adidas organized the biggest drop in Yeezy history by promising pre-sale to anyone who signed up on the website. Similar to the first release, the ‘Triple White’ 2018 model features a Primeknit upper, a Boost midsole and custom adidas and Yeezy co-branding on the insole.",
        release_date: "2017-04-29",
        sku: "CP9366",
        brand: "Adidas",
        upper_material: "Primeknit",
        main_color: "White",
        colorway: "Cream White/Cream White/Core White",
        designer: "Kanye West",
        silhouette: "Yeezy Boost 350",
        technology: "Boost",
        category: "Lifestyle"
    },
    {
        name: "Yeezy Boost 350 V2 'Black Non-Reflective'",
        description: "The adidas Yeezy Boost 350 V2 lives up to its cult appeal through evolved design elements and advanced technology. Released June 2019, this ‘Black Non-Reflective' edition's re-engineered Primeknit bootie sees futuristic updates including a translucent side stripe and bold stitching on the heel pull. Integrated lacing customizes the fit while a translucent black Boost-equipped midsole complements the covert feel.",
        release_date: "2019-06-07",
        sku: "FU9006",
        brand: "Adidas",
        upper_material: "Primeknit",
        main_color: "Black",
        colorway: "Black/Black/Black",
        designer: "Kanye West",
        silhouette: "Yeezy Boost 350",
        technology: "Boost",
        category: "Lifestyle"
    },
    {
        name: "Yeezy Boost 700 'Analog'",
        description: "Music and fashion icon Kanye West debuted the Yeezy Boost 700 at his Yeezy Season 5 fashion show in February 2017. This 'Analog' colorway released April 2019, and provides a monochromatic look to the acclaimed shoe. Dressed in shades of white, leather, mesh and suede panels come together to construct its upper. Down below, full-length Boost cushioning provides a responsive feel, built inside the 700's signature chunky midsole.",
        release_date: "2019-04-27",
        sku: "EG7596",
        brand: "Adidas",
        upper_material: "Suede",
        main_color: "Cream",
        colorway: "Analog/Analog/Analog",
        designer: "Kanye West",
        silhouette: "Yeezy Boost 700",
        technology: "Boost",
        category: "Lifestyle"
    },
    {
        name: "Yeezy Boost 700 'Utility Black'",
        description: "The Yeezy Boost 700, designed by music and fashion icon Kanye West, first debuted at the Yeezy Season 5 fashion show in February 2017. This 'Utility Black' colorway from June 2019 sees the design in a mesh upper with both plush suede and smooth leather overlays. At the bottom, the Yeezy Boost 700's chunky midsole encapsulates adidas' revolutionary Boost cushioning in a full-length format, underscored by gum rubber tread.",
        release_date: "2019-06-28",
        sku: "FV5304",
        brand: "Adidas",
        upper_material: "Suede",
        main_color: "White",
        colorway: "Utility Black/Utility Black/Utility Black",
        designer: "Kanye West",
        silhouette: "Yeezy Boost 350",
        technology: "Boost",
        category: "Lifestyle"
    },
    {
        name: "Yeezy Boost 700 'Mauve'",
        description: "The Yeezy Boost 700 ‘Mauve’ takes on a somber color scheme that blends black and purplish grey across its signature multi-layered upper. The complex arrangement sees different varieties of mesh complemented with suede and textured leather paneling, all resting upon a tonal sculpted midsole accented with pops of neon green. Exterior branding is limited to subtly visible Three-Stripes on the quarter panel and an adidas logo embossed on the outsole.",
        release_date: "2018-10-27",
        sku: "EE9614",
        brand: "Adidas",
        upper_material: "Suede",
        main_color: "Brown",
        colorway: "Mauve/Mauve/Mauve",
        designer: "Kanye West",
        silhouette: "Yeezy Boost 700",
        technology: "Boost",
        category: "Lifestyle"
    },
    {
        name: "Yeezy Boost 350 V2 'Lundmark Non-Reflective'",
        description: "The Yeezy Boost 350 V2 'Lundmark Non-Reflective' offers a modern-neutral take on Kanye West's 350 silhouette that debuted in 2015. The 'Lundmark' model features a cream-colored Primeknit upper with a translucent window along the lateral. Notably, this shoe does without the heel-tab that has been a staple on previous Yeezy Boost 350 releases. At the bottom, the sneaker's full-length adidas Boost cushioning is encapsulated within a TPU cage that extends from the midsole down to the outsole.",
        release_date: "2019-07-13",
        sku: "FU9161",
        brand: "Adidas",
        upper_material: "Primeknit",
        main_color: "Cream",
        colorway: "Lundmark/Lundmark/Lundmark",
        designer: "Kanye West",
        silhouette: "Yeezy Boost 350",
        technology: "Boost",
        category: "Lifestyle"
    },
    {
        name: "Yeezy Boost 350 V2 'Clay'",
        description: "The adidas Yeezy Boost 350 V2 ‘Clay’ updates the silhouette with a warm palette and semi-translucent, three-tone vent at the side. This ‘Clay’ colorway retains the stand-out features of the original 350 V2 shoe, first seen in September 2016, including a flexible Primeknit upper and full-length Boost cushioning. This shoe released March 2019 exclusively in select cities in North America and Latin America.",
        release_date: "2019-03-29",
        sku: "EG7490",
        brand: "Adidas",
        upper_material: "Primeknit",
        main_color: "Tan",
        colorway: "Clay/Clay/Clay",
        designer: "Kanye West",
        silhouette: "Yeezy Boost 350",
        technology: "Boost",
        category: "Lifestyle"
    },
    {
        name: "Yeezy Boost 350 V2 'Blue Tint'",
        description: "The 5th Yeezy to drop since November 2017 — Yeezy Boost 350 V2 'Semi Frozen Yellow' and ‘Beluga 2.0,’ Yeezy Powerphase Calabasas, and the Yeezy 500 ‘Desert Rat’ — the Yeezy Boost 350 V2 'Blue Tint' was dropped on December 16th, 2017. The sneaker features a neutral white and grey upper with a red ‘SPLY-350’ text on the side in reverse. The shoe also comes with a heel tab, blue tint inner lining, and paste blue laces.",
        release_date: "2017-12-16",
        sku: "B37571",
        brand: "Adidas",
        upper_material: "Primeknit",
        main_color: "Blue",
        colorway: "Blue Tint/Grey Three/High Resolution Red",
        designer: "Kanye West",
        silhouette: "Yeezy Boost 350",
        technology: "Boost",
        category: "Lifestyle"
    },
    {
        name: "Yeezy Boost 350 V2 'Beluga 2.0'",
        description: "With its name coming from the colorway similarities found on the first Yeezy Boost 350 V2, the Yeezy Boost 350 V2 'Beluga 2.0' dropped on November 25, 2017. It was quickly restocked on November 30th after selling out. The shoe features a muted grey stripe on the laterals instead of the bright orange stripe found on the original ‘Beluga’ sneaker. The Yeezy Boost 350 V2 'Beluga 2.0' also features a heel pull tab with orange stitching and orange ‘SPLY-350’ lettering in reverse on the laterals.",
        release_date: "2017-11-25",
        sku: "AH2203",
        brand: "Adidas",
        upper_material: "Primeknit",
        main_color: "Grey",
        colorway: "Grey/Bold Orange/Dark Solid Grey",
        designer: "Kanye West",
        silhouette: "Yeezy Boost 350",
        technology: "Boost",
        category: "Lifestyle"
    },
    {
        name: "Yeezy Boost 350 V2 'Semi Frozen Yellow'",
        description: "Kanye West’s Yeezy Boost 350 V2 in Semi Frozen Yellow first hit stores in November 2017, with a restock that released on December 14, 2018. Dressed in adidas’ signature Primeknit upper, the lifestyle runner is finished in an energetic bright yellow hue, one that extends to the laces, heel tab, and Boost-infused ribbed rubber midsole. Zebra-like black stripes add another design dimension to the upper, along with a tonal side stripe emblazoned with ‘SPLY 350’ in reverse red print. A gum rubber outsole adds grippy traction to the eye-catching design.",
        release_date: "2017-11-18",
        sku: "B37572",
        brand: "Adidas",
        upper_material: "Primeknit",
        main_color: "White",
        colorway: "Semi Frozen Yellow/Raw Steel/Red",
        designer: "Kanye West",
        silhouette: "Yeezy Boost 350",
        technology: "Boost",
        category: "Lifestyle"
    },
    {
        name: "Yeezy Boost 350 V2 'Bred'",
        description: "First released on February 11, 2017, the Yeezy Boost 350 V2 ‘Bred’ combines a black Primeknit upper with red SPLY 350 branding, and a translucent black midsole housing full-length Boost. This colorway of Yeezy Boost 350 V2 remains one of the most coveted Yeezy's in existence.",
        release_date: "2017-02-11",
        sku: "CP9652",
        brand: "Adidas",
        upper_material: "Primeknit",
        main_color: "White",
        colorway: "Core Black/Core Black/Red",
        designer: "Kanye West",
        silhouette: "Yeezy Boost 350",
        technology: "Boost",
        category: "Lifestyle"
    },
    {
        name: "Yeezy 500 'Utility Black'",
        description: "Kanye West and adidas launched the Yeezy 500 ‘Utility Black’ in July 2018. The retro-inspired silhouette counterbalances its bulky form with a sleek, all-black design. What sets this colorway apart from the standard triple-black finish is a singular use of tone – it’s a semi-faded black that coats the combination mesh and suede upper, as opposed to the pitch-black variety that’s more common in the sneaker firmament.",
        release_date: "2018-07-07",
        sku: "F36640",
        brand: "Adidas",
        upper_material: "Mesh",
        main_color: "Black",
        colorway: "Utility Black/Utility Black",
        designer: "Kanye West",
        silhouette: "Yezzy 500",
        technology: "Adiprene",
        category: "Lifestyle"
    },
    {
        name: "Yeezy Boost 350 V2 'Black Reflective'",
        description: "The Yeezy Boost 350 V2 was first spotted at Kanye West's Yeezy Season 3 and released in September 2016. This 'Black Reflective' colorway touched down in June 2019 and casts the shoe's flexible Primeknit upper in what appears to be a solely black hue. When hit with direct light, the shoe's laces and upper reveal powerful reflective elements that are sewn into the design. The responsive feel of full-length adidas Boost cushioning remains atop a durable rubber sole.",
        release_date: "2019-06-04",
        sku: "FU9007",
        brand: "Adidas",
        upper_material: "Primeknit",
        main_color: "White",
        colorway: "Black Reflective/Black Reflective/Black Reflective",
        designer: "Kanye West",
        silhouette: "Yeezy Boost 350",
        technology: "Boost",
        category: "Lifestyle"
    },
    {
        name: "Yeezy Boost 350 V2 'Oreo'",
        description: "Released on December 17, 2016, the Yeezy Boost 350 V2 ‘Oreo’ features a black Primeknit upper with a white stripe, SPLY 350 branding, and a translucent black midsole housing full-length Boost.",
        release_date: "2016-12-17",
        sku: "BY1604",
        brand: "Adidas",
        upper_material: "Primeknit",
        main_color: "Black",
        colorway: "Core Black/Core White/Core Black",
        designer: "Kanye West",
        silhouette: "Yeezy Boost 350",
        technology: "Boost",
        category: "Lifestyle"
    },
    {
        name: "Yeezy Boost 350 'Pirate Black' 2016",
        description: "Released on February 15th, 2016, the Yeezy Boost 350 ‘Pirate Black’ 2016 is identical to the Yeezy Boost 350 ‘Pirate Black’ 2015 release except for its upgraded padding on the inside of the heel and softer suede on its branded medial patches. The design combines a pirate black/ dark grey Primeknit upper with patterned dark grey rope laces, red accents on the heel tabs, and a black Boost outsole.",
        release_date: "2016-02-19",
        sku: "BB5350",
        brand: "Adidas",
        upper_material: "Primeknit",
        main_color: "Black",
        colorway: "Pirate Black/Blue Gray/Core Black",
        designer: "Kanye West",
        silhouette: "Yeezy Boost 350",
        technology: "Boost",
        category: "Lifestyle"
    },
    {
        name: "Yeezy Boost 350 V2 'True Form'",
        description: "Featuring a combination of neutral and earth tones, the adidas Yeezy 350 V2 ‘True Form’ is the first 350 colorway released in 2019. A soft grey hue dominates the flexible Primeknit upper with a small hit of orange behind the translucent vent on the lateral side that extends to the heel pull tab. Another hint of orange can be seen behind the ribbed TPU midsole, which houses full-length Boost cushioning. This shoe released March 2019 exclusively in select countries within Europe, as well as Russia and Ukraine.",
        release_date: "2019-03-16",
        sku: "EG7492",
        brand: "Adidas",
        upper_material: "Primeknit",
        main_color: "Grey",
        colorway: "True Form/True Form/True Form",
        designer: "Kanye West",
        silhouette: "Yeezy Boost 350",
        technology: "Boost",
        category: "Lifestyle"
    },
    {
        name: "Yeezy Boost 350 V2 'Beluga'",
        description: "Unveiled at the Yeezy Season 3 presentation at Madison Square Garden, the Yeezy Boost 350 V2 ‘Beluga’ dropped on September 24, 2016. The evolved Yeezy Boost 350 V2 silhouette features a two-tone grey Primeknit and a solar red stripe with SPLY-350 branding on the lateral side. On the medial side, the suede midfoot panel has been removed and the pull tab replaced with a new elastic fit.",
        release_date: "2016-09-24",
        sku: "BB1826",
        brand: "Adidas",
        upper_material: "Primeknit",
        main_color: "Grey",
        colorway: "Steel Grey/Beluga/Solar Red",
        designer: "Kanye West",
        silhouette: "Yeezy Boost 350",
        technology: "Boost",
        category: "Lifestyle"
    },
    {
        name: "Yeezy Boost 350 V2 'Red'",
        description: "Released on November 23, 2016, in a three-pack alongside the ‘Green’ and ‘Copper’ colorways, the Yeezy Boost 350 V2 ‘Red’ combines a black Primeknit upper with a Red stripe, SPLY 350 branding, and a translucent black midsole housing full-length Boost.",
        release_date: "2016-11-23",
        sku: "BY9612",
        brand: "Adidas",
        upper_material: "Primeknit",
        main_color: "Black",
        colorway: "White/Core Black/Red",
        designer: "Kanye West",
        silhouette: "Yeezy Boost 350",
        technology: "Boost",
        category: "Lifestyle"
    },
    {
        name: "Air Yeezy 2 SP 'Red October'",
        description: "The Air Yeezy 2 SP ‘Red October’ stands out from its two companion colorways. There’s the monochromatic scarlet finish, contrasted only by metallic gold lace tips. There’s the unique design, which sees the side panels ditch the standard anaconda texture in favor of rows upon rows of small triangular studs. Finally, there’s the chaos that surrounded the shoe’s much-delayed release. By the time the Red Octobers finally launched online with no advance notice in February 2014, Kanye West had already severed all ties with Nike.",
        release_date: "2014-02-09",
        sku: "508214 660",
        brand: "Nike",
        upper_material: "Primeknit",
        main_color: "Red",
        colorway: "Red",
        designer: "Kanye West",
        silhouette: "Air Yeezy 2",
        technology: "Boost",
        category: "Lifestyle"
    },
]

# FEAR OF GOD COLLECTION 

fear_of_god = [
    {
        name: "Air Fear of God 1 'Triple Black'",
        description: "The Air Fear of God 1 'Triple Black' showcases a stealthy monochromatic finish on Jerry Lorenzo’s street-ready basketball shoe. The upper is constructed from black ballistic mesh, reinforced with a suede toe cap and a Huarache Light-inspired TPU frame that delivers containment at the heel and midfoot. A matching black midsole reveals a double-stack Zoom unit, supplemented by internal full-length Zoom Air cushioning.",
        release_date: "2020-04-25",
        sku: "AR4237 005",
        brand: "Nike",
        upper_material: "Suede",
        main_color: "Black",
        colorway: "Black/Black",
        designer: "Jerry Lorenzo",
        silhouette: "Air Fear Of God 1",
        technology: "Air",
        category: "Basketball"
    },
    {
        name: "Air Fear of God 1 'The Question'",
        description: "Launching in February 2020, the Air Fear of God 1 'The Question' continues Jerry Lorenzo’s partnership with Nike. The designer’s stylish take on the performance basketball shoe is treated to neutral color scheme, highlighted by a black textile upper with a contrasting white toe box. The Huarache Light-inspired TPU cage is rendered in a light grey hue, while the midsole is finished in Oatmeal, complete with a visible Air window that reveals a game-changing double-stack Zoom unit.",
        release_date: "2020-02-28",
        sku: "AR4237 902",
        brand: "Nike",
        upper_material: "Suede",
        main_color: "Multi-Color",
        colorway: "Multi Color/Off Noir/String/Oatmeal",
        designer: "Jerry Lorenzo",
        silhouette: "Air Fear Of God 1",
        technology: "Air",
        category: "Basketball"
    },
    {
        name: "Air Fear Of God 1 'Oatmeal'",
        description: "Made available November 2019, the Air Fear Of God 1 'Oatmeal' was created by designer Jerry Lorenzo and Nike, updating the shoe with different earth tone hues. The shoe comes equipped with a knit high-top bootie encased in a TPU cage that pulls double duty as an eyestay anchor, stabilizing the foot with its multi-angled configuration. The translucent outsole wall peaks at the midfoot and heel for supplementary support, while double stacked Zoom Air offers premium cushioning.",
        release_date: "2019-11-02",
        sku: "AR4237 900",
        brand: "Nike",
        upper_material: "Suede",
        main_color: "Grey",
        colorway: "Multi-Color/String/Oatmeal/Pale Ivory",
        designer: "Jerry Lorenzo",
        silhouette: "Air Fear Of God 1",
        technology: "Air",
        category: "Basketball"
    },
    {
        name: "Air Fear Of God 1 'The Atmosphere'",
        description: "Style visionary Jerry Lorenzo and Nike teamed up to continue the Nike x Air Fear Of God line with this 'The Atmosphere' Fear of God 1 in July 2019 that was an exclusive SNKRS drop at ComplexCon in Chicago. The shoe's high-cut bootie upper is crafted from bold yellow mesh, reinforced with a TPU cage that allows for personalized lace reconfiguration. A tonal zipper appears on the heel to allow easier on and off, set above raised 'Fear of God' lettering. As in previous releases, this edition includes an icy, double-stacked Zoom Air unit and a concentric circle tread pattern.",
        release_date: "2019-07-21",
        sku: "AR4237 700",
        brand: "Nike",
        upper_material: "Suede",
        main_color: "Yellow",
        colorway: "Amarillo/White-Amarillo",
        designer: "Jerry Lorenzo",
        silhouette: "Air Fear Of God 1",
        technology: "Air",
        category: "Basketball"
    },
    {
        name: "Air Fear Of God 1 'Sail'",
        description: "A collaboration between Nike and fashion designer Jerry Lorenzo, the Nike Air Fear Of God 1 merges performance attributes and luxury street style. This 'Sail' version—debuted in June 2019—utilizes a mesh and suede upper with an internal heel tab. A TPU cage supports the laces, which reconfigure for a variety of looks. The matching, futuristic midsole features sidewall text for a technical look and visible double stacked Zoom Air cushioning. Concentric circle outsole tread nods to the brand's court heritage.",
        release_date: "2019-06-08",
        sku: "AR4237 100",
        brand: "Nike",
        upper_material: "Suede",
        main_color: "White",
        colorway: "Sail/Black",
        designer: "Jerry Lorenzo",
        silhouette: "Air Fear Of God 1",
        technology: "Air",
        category: "Basketball"
    },
    {
        name: "Air Fear Of God 1 'Frosted Spruce'",
        description: "The Nike Air Fear Of God 1 'Frosted Spruce' continues the procession of ultra-modern basketball footwear which began in 2018 with the first Air Fear Of God sneaker. The silhouette was created in partnership with the details-obsessed Jerry Lorenzo, originator of the Fear Of God label. This bright rendition from June 2019 features a mesh upper, a heel cage inspired by the Huarache Light and a zipper closure at the back. The shoe is supported by double-stacked Nike Zoom Air cushioning.",
        release_date: "2019-06-01",
        sku: "AR4237 300",
        brand: "Nike",
        upper_material: "Suede",
        main_color: "Green",
        colorway: "Frosted Spruce/Frosted Spruce-Frosted Spruce",
        designer: "Jerry Lorenzo",
        silhouette: "Air Fear Of God 1",
        technology: "Air",
        category: "Basketball"
    },
    {
        name: "Air Fear Of God 1 'Orange Pulse'",
        description: "In 2018, details-obsessed designer and originator of the Fear Of God label, Jerry Lorenzo, teamed up with Nike to produce the Nike Air Fear Of God sneaker. The June 2019 Nike Air Fear Of God 1 'Orange Pulse' shoe is doused in an ultra-bright Orange Pulse hue, with a mesh upper and a supportive heel cage inspired by the Huarache Light. The shoe includes broad, rope-style laces, as well as a zipper at the rear for easier on and off. Below, the design sits atop double-stacked Nike Zoom Air cushioning.",
        release_date: "2019-06-01",
        sku: "AR4237 800",
        brand: "Nike",
        upper_material: "Suede",
        main_color: "Orange",
        colorway: "Orange Pulse/Orange Pulse-Orange Pulse",
        designer: "Jerry Lorenzo",
        silhouette: "Air Fear Of God 1",
        technology: "Air",
        category: "Basketball"
    },
    {
        name: "Air Fear Of God 1 'Black'",
        description: "The Air Fear of God 1 ‘Black’ is one of the inaugural colorways of the performance basketball shoe made in collaboration between Nike and Jerry Lorenzo’s Fear of God. The fashion-forward silhouette uses a brand new last made expressly for the specific model, topped with a minimalist black leather upper with a TPU cage inspired by the Huarache Light. The tooling takes the form of a contrasting white cup sole with a visible double-stack Zoom heel unit.",
        release_date: "2018-12-15",
        sku: "AR4237 001",
        brand: "Nike",
        upper_material: "Suede",
        main_color: "Black",
        colorway: "Black/Black",
        designer: "Jerry Lorenzo",
        silhouette: "Air Fear Of God 1",
        technology: "Air",
        category: "Basketball"
    },
    {
        name: "Air Fear Of God 1 'Light Bone'",
        description: "The Air Fear of God 1 ‘Light Bone’ represents the very first collaboration between the Swoosh and Jerry Lorenzo, who worked on the unique silhouette with Nike designer Leo Chang. The performance basketball shoe features a Light Bone leather upper, supported by a tonal TPU cage inspired by the Huarache Light. The tooling showcases a visible double-stack Zoom heel unit that’s augmented by full-length Zoom cushioning.",
        release_date: "2019-01-19",
        sku: "AR4237 002",
        brand: "Nike",
        upper_material: "Suede",
        main_color: "White",
        colorway: "Light Bone/Black",
        designer: "Jerry Lorenzo",
        silhouette: "Air Fear Of God 1",
        technology: "Air",
        category: "Basketball"
    },
    {
        name: "Air Fear Of God SA 'Light Bone'",
        description: "The Air Fear of God SA ‘Light Bone' showcases Jerry Lorenzo’s take on a lifestyle basketball sneaker. The high-top is the off-court version of the similar Fear of God 1, down to the colorway, heel zip detailing and double-height Zoom Air unit. Unlike its performance counterpart, the Shoot Around features a cageless one-piece upper adorned with a Swoosh and adjustable ankle strap.",
        release_date: "2019-01-19",
        sku: "AT9915 002",
        brand: "Nike",
        upper_material: "Suede",
        main_color: "Tan",
        colorway: "Light Bone/Black",
        designer: "Jerry Lorenzo",
        silhouette: "Air Fear Of God 1",
        technology: "Air",
        category: "Basketball"
    },
    {
        name: "Air Fear Of God SA 'Black'",
        description: "The Air Fear of God SA ‘Black’ is a lifestyle take on Jerry Lorenzo’s performance-focused Nike collaboration, the Fear of God 1. The two silhouettes share the same extended collar and double-height Zoom Air unit. Featuring an all-black synthetic upper, the Shoot Around ditches the cage construction of its counterpart, while adding an ankle strap, drawcord lacing and a glossy Swoosh on the quarter panel.",
        release_date: "2018-12-15",
        sku: "AT9915 001",
        brand: "Nike",
        upper_material: "Suede",
        main_color: "Black",
        colorway: "Black/Black",
        designer: "Jerry Lorenzo",
        silhouette: "Air Fear Of God 1",
        technology: "Air",
        category: "Basketball"
    },
    {
        name: "Air Fear Of God Raid 'Black'",
        description: "Nike and frequent collaborator Fear Of God designer, Jerry Lorenzo, joined forces once again for the Air Fear Of God Raid 'Black' sneaker. Released in May 2019, the uniquely designed silhouette is inspired by one of Lorenzo’s favorite Nike designs, the Air Raid. Outfitted with a cross strap suede and textile upper above; below, its equipped with a double stacked Zoom Air unit in heel for a retro, yet futuristic finish.",
        release_date: "2019-05-17",
        sku: "AT8087 002",
        brand: "Nike",
        upper_material: "Suede",
        main_color: "Black",
        colorway: "Black/Black-Fossil",
        designer: "Jerry Lorenzo",
        silhouette: "Air Fear Of God 1",
        technology: "Air",
        category: "Basketball"
    },
    {
        name: "Air Fear Of God Raid 'Light Bone'",
        description: "Created by acclaimed streetwear designer Jerry Lorenzo for release in April 2019, the Air Fear of God Raid 'Light Bone' draws inspiration from Lorenzo's favorite silhouette, the Air Raid outdoor basketball shoe first introduced in 1992. Incorporating the same distinct cross straps into the Light Bone upper, a contrasting black Swoosh stands out along with the visible double-stacked Zoom Air units. Modern design lines combine with premium comfort to define this lifestyle shoe.",
        release_date: "2019-04-27",
        sku: "AT8087 001",
        brand: "Nike",
        upper_material: "Suede",
        main_color: "White",
        colorway: "Light Bone/Black-Sail",
        designer: "Jerry Lorenzo",
        silhouette: "Air Fear Of God 1",
        technology: "Air",
        category: "Basketball"
    },
    {
        name: "Air Fear Of God Moc 'Black'",
        description: "Known for its blend of 90s grunge with modern hip-hop style, the collaborative collection between Nike and Jerry Lorenzo’s LA-based brand, Fear Of God, released the Air Fear Of God Moc 'Black' sneaker in May 2019. The laceless silhouette features a tonal textile upper that swaps its typical laces for a toggle lacing system at heel and an elastic strap around midfoot. It's completed with a double-stacked Zoom Air unit for lightweight cushioning.",
        release_date: "2019-05-17",
        sku: "AT8086 002",
        brand: "Nike",
        upper_material: "Suede",
        main_color: "Black",
        colorway: "Black/Black-Fossil",
        designer: "Jerry Lorenzo",
        silhouette: "Air Fear Of God Moccasin",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Air Fear of God Moc 'Particle Beige'",
        description: "Continuing Jerry Lorenzo's detail-focused collection with the Swoosh brand, July 2019 saw the release of the Air Fear of God Moc 'Particle Beige' sneaker. This modern moccasin-style shoe features a laceless design with a one-piece nylon upper. A toggle at the heel, side snap and midfoot strap help provide a secure and personalized fit. Tonal stitching on the forefoot adds a subtle focal point, while an enhanced foam sole with double stacked Zoom Air keeps this shoe in line with Lorenzo's previous releases.",
        release_date: "2019-07-20",
        sku: "AT8086 200",
        brand: "Nike",
        upper_material: "Suede",
        main_color: "Cream",
        colorway: "Particle Beige/Sail-Black",
        designer: "Jerry Lorenzo",
        silhouette: "Air Fear Of God Mocassin",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Air Fear Of God Moc 'Pure Platinum'",
        description: "From streetwear fashion designer Jerry Lorenzo comes the Air Fear of God Moc 'Pure Platinum,' released on April 27th, 2019, as part of the second wave of his collaboration with Nike. With a Pure Platinum upper over a Sail midsole and outsole, this lifestyle Moc gets its bounce from stacked visible Zoom Air units in the heel. A toggle drawstring in back allows for on-the-spot adjustments to its streamlined textile upper, which features a forefoot strap for lockdown and a snap button on the side for easy on/off.",
        release_date: "2019-04-27",
        sku: "AT8086 001",
        brand: "Nike",
        upper_material: "Suede",
        main_color: "White",
        colorway: "Pure Platinum/Black-Sail",
        designer: "Jerry Lorenzo",
        silhouette: "Air Fear Of God Moccasin",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Fear Of God x Air Skylon 2 'Light Bone'",
        description: "Famed creative Jerry Lorenzo collaborated with Nike in 2018 to develop the Fear of God collection. The Air Skylon 2 'Light Bone' dropped in July 2019, featuring a luxe makeover to the vintage running silhouette with a mesh and suede upper. Adding metallic accents and transparent detailing, the shoe incorporates performance with an ethereal feel.",
        release_date: "2019-07-20",
        sku: "BQ2752 003",
        brand: "Nike",
        upper_material: "Suede",
        main_color: "Cream",
        colorway: "Light Bone/Clear-Reflect",
        designer: "Jerry Lorenzo",
        silhouette: "Air Skylon 2",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Fear Of God x Air Skylon 2 'White'",
        description: "Jerry Lorenzo updates the classic Air Skylon 2 in this collaboration with his Fear of God brand. A white textile base is complemented by tonal leather and suede overlays, along with a patent leather Swoosh in contrast black. Underneath the toggle lacing system is an unbranded perforated leather tongue in matching white.",
        release_date: "2018-12-27",
        sku: "BQ2752 100",
        brand: "Nike",
        upper_material: "Suede",
        main_color: "Black",
        colorway: "White/Black-Light Bone-Sail",
        designer: "Jerry Lorenzo",
        silhouette: "Air Skylon 2",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Fear Of God x Air Skylon 2 'Black'",
        description: "Nike teamed up with Fear of God’s Jerry Lorenzo to released an updated iteration of the Skylon 2 silhouette. The Fear Of God x Air Skylon 2 'Black' features a mesh-based upper in an all-black color scheme with matching leather and patent leather details. The low top also boasts mesh padding on the tongue for breathability, a toggle lacing system for a personalized fit, and Fear of God branding on the heel side and insole.",
        release_date: "2018-12-27",
        sku: "BQ2752 001",
        brand: "Nike",
        upper_material: "Suede",
        main_color: "Black",
        colorway: "Black/Anthracite-Pearl White-White",
        designer: "Jerry Lorenzo",
        silhouette: "Air Skylon 2",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Fear of God x Chuck 70 Hi 'Natural'",
        description: "Released as part of Jerry Lorenzo’s ‘Essentials’ diffusion line, the Fear of God x Chuck 70 High ‘Natural’ makes use of a classic canvas and rubber build. The off-white upper features chrome eyelets and a traditional All Star patch on the medial-side collar. The shoe’s tongue and rubber toe cap are finished in contrasting black, while the rubber midsole repeats the same black and off-white color scheme.",
        release_date: "2018-12-12",
        sku: "164530C",
        brand: "Converse",
        upper_material: "Suede",
        main_color: "Cream",
        colorway: "Natural/Natural/Black",
        designer: "Jerry Lorenzo",
        silhouette: "Chuck Taylor All Star",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Fear of God x Chuck 70 Hi 'Black'",
        description: "Fear of God creator Jerry Lorenzo collaborated with Converse for this take on the Chuck 70 High, applying his signature black and off-white color blocking. Featuring a classic canvas upper construction, the shoe reworks the lacing system to wrap around the ankle, a traditional look among Converse purists. The sneaker is finished with co-branded license plates.",
        release_date: "2018-12-12",
        sku: "164529C",
        brand: "Converse",
        upper_material: "Suede",
        main_color: "Black",
        colorway: "Black/Black/Natural",
        designer: "Jerry Lorenzo",
        silhouette: "Chuck Taylor All Star",
        technology: "Air",
        category: "Lifestyle"
    },
]

styles_page = [
    {
        name: "Air Jordan 1 Retro High OG 'Shattered Backboard 3.0'",
        description: "The Air Jordan 1 Retro High OG 'Shattered Backboard 3.0' revisits a coveted colorway inspired by a Michael Jordan backboard-breaking dunk that took place during a 1985 Nike exhibition game. The shoe's colorway of black, Pale Vanilla and Starfish matches the colors of the jersey MJ sported that day. Released in October 2019, this third edition of the sneaker features a crinkled, glossy patent leather upper that alludes to the hoop's broken glass, a fitting tribute to an early iconic moment.",
        release_date: "2019-10-26",
        sku: "555088 028",
        brand: "Air Jordan",
        upper_material: "Patent Leather",
        main_color: "Black",
        colorway: "Black/Pale Vanilla-Starfish",
        designer: "Peter Moore",
        silhouette: "Air Jordan 1",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Air Jordan 1 Retro High OG NRG 'Gold Top 3'",
        description: "The Nike Air Jordan Retro High OG NRG in ‘Gold Top 3’ was initially an exclusive release at ComplexCon, and then was subsequently released online for Cyber Monday 2017. The Air Jordan 1's coveted black and metallic gold patent colorway is re-imagined in this mis-matched patent leather construction, an homage to the Air Jordan 1 'Top 3' sneaker from 2016.",
        release_date: "2017-11-27",
        sku: "861428 001",
        brand: "Air Jordan",
        upper_material: "Patent Leather",
        main_color: "Gold",
        colorway: "Black/Black-Metallic Gold",
        designer: "Peter Moore",
        silhouette: "Air Jordan 1",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Air Jordan 1 Retro High OG 'Bred Toe'",
        description: "Arriving in stores in February 2018, the Air Jordan 1 Retro High OG ‘Bred Toe’ is a new spin on a classic design. The Chicago Bulls-inspired colorway combines elements of the ‘Bred’ and ‘Black Toe’ editions of the Air Jordan 1, executed on a premium leather build. The high-top features a black Swoosh on the white quarter panel, along with contrasting pops of red on the toe box, heel, collar, and outsole. The shoe stays true to its OG 1985 roots with Nike Air branding on the tongue tag and sockliner.",
        release_date: "2018-02-24",
        sku: "555088 610",
        brand: "Air Jordan",
        upper_material: "Leather",
        main_color: "Red",
        colorway: "Gym Red/Summit White-Black",
        designer: "Peter Moore",
        silhouette: "Air Jordan 1",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Air Jordan 11 Retro 'Cool Grey' 2001",
        description: "Michael Jordan wore the Air Jordan 11 Retro 'Cool Grey' 2001 multiple times, including when he won against the New York Knicks at Madison Square Garden as a member of the Washington Wizards. A new addition to the lineage of the Air Jordan 11, the high-performing mid-top features a Cool Grey nubuck upper with patent leather along the mudguard. The sneaker also boasts a quick lace system, carbon fiber sheath, and classic Jumpman branding at the heel.",
        release_date: "2001-03-03",
        sku: "136046 011",
        brand: "Air Jordan",
        upper_material: "Leather",
        main_color: "Grey",
        colorway: "Medium Grey/White-Cool Grey",
        designer: "Tinker Hatfield",
        silhouette: "Air Jordan 11",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Air Jordan 1 Retro High OG 'Royal' 2017",
        description: "In 1985 sports photographer, Chuck Kohn, photographed Michael Jordan wearing the Air Jordan 1 Royals. This photo turned Nike poster was the first time anyone saw Michael wearing the Air Jordan 1 sneakers. Ever. Known to be his favorite colorway, Jordan chose the Royals to be the first Air Jordan 1 available for purchase. They were also the only color-way out of the Top 3 Air Jordan 1 Retro colorways (‘Banned’ and ‘Chicago’) that he never wore on the court. Since 1985, the Royals have been released in 2001, 2013, and 2017.",
        release_date: "2017-04-01",
        sku: "555088 007",
        brand: "Air Jordan",
        upper_material: "Leather",
        main_color: "Black",
        colorway: "Black/Royal-White",
        designer: "Peter Moore",
        silhouette: "Air Jordan 1",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Travis Scott x Air Jordan 1 Retro High OG 'Mocha'",
        description: "The Travis Scott x Air Jordan 1 Retro High features a new look on the iconic silhouette, thanks to an oversized backward-facing Swoosh on the lateral side. A traditionally oriented Swoosh graces the medial side of the upper, which is built with a blend of white leather and brown suede. Additional unique details include a double-layer construction on the collar and Scott’s crudely drawn face logo embossed on the heel.",
        release_date: "2019-05-11",
        sku: "CD4487 100",
        brand: "Air Jordan",
        upper_material: "Leather",
        main_color: "Brown",
        colorway: "Sail/Dark Mocha-University Red-Black",
        designer: "Peter Moore",
        silhouette: "Air Jordan 1",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Travis Scott x Air Jordan 6 Retro 'Olive'",
        description: "The Travis Scott x Air Jordan 6 Retro 'Olive' represents a collaboration between the Houston based rapper and Jordan Brand. This take on the AJ 6, which Scott debuted while performing during halftime of Super Bowl 53, released in October 2019. It features a Medium Olive, black, Sail and University Red colorway along with several unique elements: a small pocket with a snap on the collar, a nubuck and suede upper, Scott's 'Cactus Jack' logo on the heel and a glow-in-the-dark translucent outsole.",
        release_date: "2019-10-11",
        sku: "CN1084 200",
        brand: "Air Jordan",
        upper_material: "Nubuck",
        main_color: "Green",
        colorway: "Medium Olive/Black-Sail-University Red",
        designer: "Tinker Hatfield",
        silhouette: "Air Jordan 6",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Travis Scott x Air Jordan 1 Low 'Mocha'",
        description: "Travis Scott and Jordan Brand collaborate on an Air Jordan 1 Low, taking similar design cues from the high-top version. An oversized backward facing Swoosh is featured prominently on the lateral side of the shoe, while a regular Swoosh graces the medial side. Black and Dark Mocha nubuck dominate the upper, with a few pops of University Red adding a nice contrast. Travis Scott details are subtly placed on the shoe, with the ‘Cactus Jack’ logo appearing on the tongue, medial side panel and sockliner. The back heel tabs feature intricately stitched logos, with the Air Jordan Wings on the right shoe and Scott’s crudely drawn face on the left shoe.",
        release_date: "2019-07-19",
        sku: "CQ4277 001",
        brand: "Air Jordan",
        upper_material: "Leather",
        main_color: "Brown",
        colorway: "Black/Dark Mocha-University Red-Sail",
        designer: "Peter Moore",
        silhouette: "Air Jordan 1",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Travis Scott x Air Jordan 4 Retro 'Cactus Jack'",
        description: "Music artist Travis Scott hails from Houston, where the Oilers used to take the field in red, white and blue uniforms. The Travis Scott x Air Jordan 4 Retro 'Cactus Jack' colorway pays tribute to the city’s bygone football team with a Durabuck leather upper dressed in University Blue and a Varsity Red insole. The black lace cage and a heel panel feature a light blue speckle pattern. Cactus Jack branding appears on the left heel in Varsity Red, with a matching Jumpman logo on the right.",
        release_date: "2018-06-09",
        sku: "308497 406",
        brand: "Air Jordan",
        upper_material: "Leather",
        main_color: "Blue",
        colorway: "University Blue/Varsity Red-Black",
        designer: "Tinker Hatfield",
        silhouette: "Air Jordan 4",
        technology: "Air",
        category: "Lifestyle"
    },
    {
        name: "Air Jordan 1 Retro High OG 'Banned' 2016",
        description: "Banned by the NBA in 1985, Michael Jordan was charged $5,000 per game for wearing the Air Jordan 1 ‘Black/Red' because they didn’t include the color white which was part of the Chicago Bulls’ official team colors. Used as a marketing tactic, Nike crafted the ‘Banned’ campaign around the sneakers to launch and promote the Air Jordan line. The sneaker was retroed in 1994, 2011, 2013 and 2016. The 2011 pair featured an ‘X’ on the heel paying homage to the 'Banned' nickname.",
        release_date: "2016-09-02",
        sku: "555088 001",
        brand: "Air Jordan",
        upper_material: "Leather",
        main_color: "Black",
        colorway: "Black/Varsity Red-White",
        designer: "Peter Moore",
        silhouette: "Air Jordan 1",
        technology: "Air",
        category: "Lifestyle"
    },
]

require 'open-uri'

the_last_dance.each { |sneaker| Sneaker.create!(sneaker) }
off_white.each { |sneaker| Sneaker.create!(sneaker) }
yeezy_collection.each { |sneaker| Sneaker.create!(sneaker) }
fear_of_god.each { |sneaker| Sneaker.create!(sneaker) }
styles_page.each { |sneaker| Sneaker.create!(sneaker) }

Sneaker.all.each do |sneaker|
  sku = sneaker[:sku].split(" ").join("")
  photo = open("https://sneaker-photos.s3-us-west-1.amazonaws.com/#{sku}.jpg")

  sneaker.photo.attach(
    io: photo, 
    filename: "#{sku}.jpg"
  )
end

# Listings 
sizes = [4.5, 5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 12.5, 13]

#Price generator 
def price_generator(min, max) 
    prices = []
    (min..max).each do |price|
        prices << price
    end 
    return prices.sample
end

#Listings generator 

Sneaker.all.each do |sneaker|
    sizes.each do |size|
        Listing.create!({sneaker_id: sneaker[:id], size: size, price: price_generator(200,500), user_id: 1})
    end
end